# Generated by Django 5.2.10 on 2026-01-14 02:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Doc',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doc_key', models.CharField(db_index=True, max_length=255, unique=True)),
                ('title', models.TextField(blank=True, default='')),
                ('slug', models.CharField(blank=True, db_index=True, default='', max_length=255)),
                ('tags', models.JSONField(blank=True, default=list)),
                ('html', models.TextField(blank=True, default='')),
                ('content_hash', models.CharField(db_index=True, max_length=64)),
                ('client_version', models.IntegerField(default=0)),
                ('client_updated_at', models.DateTimeField(blank=True, null=True)),
                ('server_version', models.BigIntegerField(default=0)),
                ('server_updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='DocHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('server_version', models.BigIntegerField()),
                ('content_hash', models.CharField(max_length=64)),
                ('html', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('doc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history', to='contentapi.doc')),
            ],
        ),
    ]
