# Generated by Django 5.2.9 on 2026-01-15 22:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='NotebookEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doc_key', models.CharField(db_index=True, help_text='Stable document key from client (qmd/sqlite pipeline)', max_length=255, unique=True)),
                ('title', models.TextField(blank=True, default='')),
                ('slug', models.CharField(blank=True, db_index=True, default='', max_length=255)),
                ('tags', models.JSONField(blank=True, default=list, help_text='List of tag strings')),
                ('html', models.TextField(blank=True, default='', help_text='Rendered HTML fragment (trusted)')),
                ('content_hash', models.CharField(db_index=True, help_text='Hash of canonical content for sync', max_length=64)),
                ('client_version', models.IntegerField(default=0, help_text='Client-side version counter')),
                ('client_updated_at', models.DateTimeField(blank=True, help_text='Timestamp from client', null=True)),
                ('server_version', models.BigIntegerField(default=0, help_text='Server-side version counter')),
                ('server_updated_at', models.DateTimeField(auto_now=True, help_text='Last time server touched this row')),
            ],
            options={
                'db_table': 'notebook_entry',
                'ordering': ['-server_updated_at'],
            },
        ),
    ]
