# Generated by Django 5.2.9 on 2026-01-15 23:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_notebookentry'),
    ]

    operations = [
        migrations.DeleteModel(
            name='NotebookEntry',
        ),
    ]
